### ISSUE TITLE
Problema com o cadastramento de alunos por arquivo.

### ISSUE THREAD

**Issue by wildevn** [LinaxT25/Work-of-AlgProgII#2]
O cadastramento de alunos por arquivo sem qualquer aluno previamente cadastrado manualmente gera um problema que acaba fechando o programa, ou simplesmente (segmentation fault).

**Comment by LinaxT25** [comment]
Esse tem que resolver urgente duvido que a professora vai cadastrar primeiro, pra depois usar a opção de cadastrar geral, se mais tarde der tempo eu tento dar uma olhada, marquei o @FilipePires17 tanto aqui como no bug, pra ver se ele recebe o aviso.

**Comment by wildevn** [comment]
poise, to a um bom tempo olhando ele
mas ate o momento não achei nd
